### ISSUE TITLE
crappy UX in IE10

### ISSUE THREAD

**Issue by nkritsky** [bedrin/jdbc-sniffer#80]
When using j-s in IE10 it does not look pretty.
1. database icon is not shown.
2. number is left-aligned.
3. Executed queries pop-up is not popping up.

Env:
Win7 Enterprise
IE10

**Comment by bedrin** [comment]
Sniffer should be inserted before closing </html> tag 
Otherwise it is renderred crappy in IE

**Comment by bedrin** [comment]
Fixed in 2.3.5
